server { 
    listen 80;
    server_name test-production-b686.up.railway.app;

    # Редирект на HTTPS с сохранением пути и квери-параметров
    location / {
        return 301 https://$host$request_uri;
    }
}
