server {
    listen 80;
    server_name test-production-e806.up.railway.app;

    # Редирект на HTTPS с сохранением пути и квери-параметров
    location / {
        return 308 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name test-production-e806.up.railway.app;

    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    location / {
        default_type application/json;
        return 200 '{"status":"ok","message":"Hello from Railway!"}';
    }
}
