events {}
http {
  server {
    listen 80;
    server_name your-subdomain.up.railway.app;

    location / {
      proxy_pass http://your-backend:port;
      proxy_set_header Host $host;
    }
  }
}